# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20171110_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.UserProfile'),
        ),
    ]
