# Generated by Django 2.0 on 2017-12-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20171214_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='solution',
            name='file',
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=True, to='application.UserProfile'),
        ),
        migrations.AddField(
            model_name='solution',
            name='body',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='solution',
            name='points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='solution',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='identity',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], default='student', max_length=100),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(default='', on_delete=True, to='application.Course'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='courses',
            field=models.ManyToManyField(to='application.Course'),
        ),
    ]
