# Generated by Django 2.0 on 2017-12-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20171214_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(choices=[('Math', 'Math'), ('English', 'English'), ('Physics', 'Physics')], default='', max_length=100),
        ),
    ]
