# Generated by Django 2.0 on 2017-12-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20171214_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='courses',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='courses',
            field=models.CharField(default='', max_length=500),
        ),
    ]
