# Generated by Django 2.0 on 2017-12-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20171215_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='comments',
            field=models.CharField(default='', max_length=200),
        ),
    ]
