# Generated by Django 2.0 on 2017-12-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_solution_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='worked',
            field=models.BooleanField(default=False),
        ),
    ]
