# Generated by Django 2.0 on 2018-01-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_solution_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='num',
            field=models.IntegerField(default=1),
        ),
    ]
